### ISSUE TITLE
【Bug】Screen scrolls automatically

### ISSUE THREAD

**Issue by taka-0770** [SignalFlagZ/sd-civitai-browser#11]
Bug in 1.7.5? It looks like this, but when you click on the image displayed in get list, the screen automatically moves a little to the bottom. This is a bug confirmed in brave and chrome
I don't know how to paste it, so
https://i.imgur.com/SsBB0ID.mp4
I feel like this

**Comment by SignalFlagZ** [comment]
Thank you for reporting. 
That is by design.  I changed the behavior because a back-to-top button was added.

**Comment by taka-0770** [comment]
If possible, it would be two years ago now, but I would be happy if you could return to the same behavior as two years ago. I don't know what changed in the design between the behavior before the update and the behavior after the update.
I am currently using the previous version, but it would be helpful if you could fix the behavior
If you click on card number 0, it will not move.

**Comment by SignalFlagZ** [comment]
日本語でおk

**Comment by taka-0770** [comment]
日本語で良いとの事ですので日本語で書きます。２つ前の更新まではbraveでもTOPに戻る表示で戻れる様になったので凄く
嬉しかったです。しかし、その後の更新で一番最初にリストを表示した場合にカードをクリックした時は下に下がる挙動は無いのに２回目以降は下がります。ページを変えた場合も１度目は下がらないのに２回目以降は下がります。挙動としては少し不便なので現在は２つ前のバージョンを利用させて頂いています。出来れば挙動を戻して頂けると助かります。

**Comment by SignalFlagZ** [comment]
There are various user environments such as screen size, resolution, display magnification, and font size. You can also set the number of cards and card size.
In many cases, the screen will not change when you click on the card. Because the model information is off-screen. A UI that does not respond to user actions is something that should be avoided. Clicking on the card indicates that you want to see model information. So scroll down to model information.
Depending on your settings, this may not be necessary. I don't do optimization for specific environments. However, it might be nice to be able to select the behavior in Settings.
Fixed the scroll position to be the same every time.
